FROM python:3.10-slim

WORKDIR /app

COPY very_simple_app.py app.py
COPY requirements.very_simple.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p templates

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
