version: '3.8'

services:
  app:
    build: .
    container_name: network-security-ai
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-pro}
      - DEBUG=${DEBUG:-False}
    restart: unless-stopped
