name: Deploy Enhanced Network Security API

on:
  push:
    branches:
      - main
    paths:
      - 'enhanced_very_simple_app.py'
      - 'Dockerfile.enhanced'
      - 'deploy_enhanced.sh'
      - '.github/workflows/deploy_enhanced.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Extract hostname without port if it contains a colon
          EC2_HOSTNAME=$(echo "${{ secrets.EC2_HOST }}" | cut -d: -f1)
          echo "Using hostname: $EC2_HOSTNAME for SSH keyscan"
          ssh-keyscan -H "$EC2_HOSTNAME" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          python deploy.py --key ~/.ssh/id_rsa --host ${{ secrets.EC2_HOST }} --enhanced

      - name: Test application
        run: |
          # Wait for the application to start
          sleep 10

          # Test the root endpoint
          ROOT_RESPONSE=$(curl -s http://${{ secrets.EC2_HOST }}:8000/)
          echo "Root endpoint response: $ROOT_RESPONSE"

          if [[ "$ROOT_RESPONSE" == *"Network Security API is running"* ]]; then
            echo "✅ Root endpoint check passed"
          else
            echo "❌ Root endpoint check failed"
            exit 1
          fi

          # Test the health endpoint
          HEALTH_RESPONSE=$(curl -s http://${{ secrets.EC2_HOST }}:8000/health)
          echo "Health endpoint response: $HEALTH_RESPONSE"

          if [[ "$HEALTH_RESPONSE" == *"healthy"* ]]; then
            echo "✅ Health endpoint check passed"
          else
            echo "❌ Health endpoint check failed"
            exit 1
          fi
