name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Lint Code
        run: |
          echo "Running pylint..."
          pylint --rcfile=.pylintrc $(git ls-files '*.py') || true

      - name: Run Unit Tests
        run: |
          echo "Running pytest..."
          pytest -v --tb=short --disable-warnings --maxfail=1 --cov=src --cov-report=xml --cov-report=html --cov-report=term-missing -p no:warnings tests/ || true
          echo "Generating coverage report..."